version: "3.9"

services:
  btc:
    image: ruimarinho/bitcoin-core:23.0
    container_name: btc
    restart: always
    expose:
      - "28333"
      - "28332"
    ports:
      - "28333:28333"
      - "28332:28332"
    volumes:
      - ${HOME}/.bitcoin/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
      - ${HOME}/.bitcoin/move.sh:/bitcoin/.bitcoin/move.sh
      - bitcoin:/bitcoin/.bitcoin/ # data persistence
    networks:
      - btc-network

  torproxy:
    image: dperson/torproxy
    container_name: torproxy
    restart: unless-stopped
    networks:
      - lnd-network

  lnd:
    image: lightninglabs/lnd:v0.14.5-beta
    container_name: lnd
    restart: always
    ports:
      - "10009:10009"
      - "9009:9735"
      - "9735:9735"
    volumes:
      - ./lnd/lnd.conf:/lnd/.lnd/lnd.conf
      - bitcoin:/lnd/.bitcoin/
      - lnd:/lnd/.lnd/ # data persistence
    command:
      --noseedbackup
      --debuglevel=debug
      --maxpendingchannels=10
      --rpclisten=0.0.0.0:10009
      --color=#4126a7
      --alias=LND
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=btc
      --bitcoind.rpcuser=testuser
      --bitcoind.rpcpassword=$mbncjnna`Lqaxo#^f5W``^v7fsT7kuz
      --bitcoind.zmqpubrawblock=tcp://btc:28332
      --bitcoind.zmqpubrawtx=tcp://btc:28333
      --adminmacaroonpath=/lnd/.lnd/admin.macaroon
      --readonlymacaroonpath=/lnd/.lnd/readonly.macaroon
      --invoicemacaroonpath=/lnd/.lnd/invoice.macaroon
      --tor.active
      --tor.socks=torproxy:9050
      --tor.streamisolation=false
      --tor.v3
      --tor.control=torproxy:9051
      --listen=localhost
      --listen=torproxy
      # --externalip=88.135.143.213
      # --tlsextraip=88.135.143.213
      # --tor.skip-proxy-for-clearnet-targets=1
    networks:
      - btc-network
      - lnd-network

  litd:
    image: lightninglabs/litd
    container_name: litd
    restart: always
    ports:
      - "8443:8443"
      - "11010:11010" # loopd
      - "12010:12010" # poold
      - "8465:8465" # faraday
    volumes:
      - ./lit/lit.conf:/lit/.lit/lit.conf
      - lnd:/lnd/.lnd/
      - lit:/lit/.lit/
    command:
      --httpslisten=0.0.0.0:8443
      --uipassword=KQ5NhyL#HWsSuMquqXjLb5DjT3S^iKt5
      --lit-dir=/lit/.lit
      --network=testnet
      --remote.lit-debuglevel=debug
      --remote.lnd.rpcserver=lnd:10009
      --remote.lnd.macaroonpath=/lnd/.lnd/admin.macaroon
      --remote.lnd.tlscertpath=/lnd/.lnd/tls.cert
      --loop.loopoutmaxparts=5
      --pool.newnodesonly=true
      --faraday.min_monitored=48h
      --faraday.connect_bitcoin
      --faraday.bitcoin.host=btc:28332
      --faraday.bitcoin.user=testuser
      --faraday.bitcoin.password=$mbncjnna`Lqaxo#^f5W``^v7fsT7kuz
    networks:
      - btc-network

networks:
  btc-network:
    name: btc-network
    driver: bridge
  lnd-network:
    name: lnd-network
    driver: bridge

volumes:
  bitcoin: # docker volume create bitcoin
    external: true
  lnd:
  lit: